version: "3.8"

services:
  db:
    image: postgres:alpine
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - "8081:5432"
    volumes:
      - postgres-db:/var/lib/postgresql/data
    networks:
      - spotiflix
  api:
    depends_on:
      - db
    environment:
      - SECRET_STRING=${SECRET_STRING}
    build: ./
    ports:
      - "8080:8080"
    networks:
      - spotiflix
    volumes:
      - ./:/app/spotiflix/
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    networks:
      - spotiflix

networks:
  spotiflix:
volumes:
  postgres-db: